server:
  port: 52001
  servlet:
    context-path: /

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.default_schema: public
      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://cornelius.db.elephantsql.com:5432/fmxvhdzn
    username: fmxvhdzn
    password: RF8CxIVVPxjDxi2btDifmS5z-1CU3K4r